// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shortener.Data;

namespace shortener.Migrations
{
    [DbContext(typeof(SHSHConnector))]
    partial class SHSHConnectorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("shortener.Data.ShortLink", b =>
                {
                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Redirect")
                        .HasColumnType("TEXT");

                    b.HasKey("Link");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
